category_list:
    path:	/category/{page}
    defaults:	{ _controller: HROMGalleryBundle:GalleryAdmin:list, page: 1 }
    requirements:
        page:	(([1-9])+([0-9])*)

category_add:
    path: /category/add
    defaults: { _controller: HROMGalleryBundle:GalleryAdmin:add }
    
category_edit:
    path: /category/edit/{id}
    defaults: { _controller: HROMGalleryBundle:GalleryAdmin:edit }
    requirements:
        id: \d+

category_delete:
    path:	/category/delete/{id}
    defaults:	{ _controller: HROMGalleryBundle:GalleryAdmin:delete }
    requirements:
        id:	\d+