parameters:
#    hrom_gallery.example.class: HROM\GalleryBundle\Example

services:
#    hrom_gallery.example:
#        class: %hrom_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
