parameters:
#    hrom_user.example.class: HROM\UserBundle\Example

services:
#    hrom_user.example:
#        class: %hrom_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
