parameters:
#    hrom_contacts.example.class: HROM\ContactsBundle\Example

services:
#    hrom_contacts.example:
#        class: %hrom_contacts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
