parameters:
#    hrom_admin.example.class: HROM\AdminBundle\Example

services:
#    hrom_admin.example:
#        class: %hrom_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
