<?php

namespace HROM\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {
    public function count() {
        $qb = $this->_em->createQueryBuilder();

        $qb
                ->select('count(category)')
                ->from('HROMGalleryBundle:Category', 'category');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
