#Webmaster
hrom_webmaster:
    resource: "@HROMWebmasterBundle/Resources/config/routing.yml"
    prefix:   /wm

#Admin
hrom_admin:
    resource: "@HROMAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
#Core
hrom_core:
    resource: "@HROMCoreBundle/Resources/config/routing.yml"
    prefix:   /

#Contacts
hrom_contacts:
    resource: "@HROMContactsBundle/Resources/config/routing.yml"
    prefix:   /contacts
    
hrom_contacts_admin:
    resource: "@HROMContactsBundle/Resources/config/admin.yml"
    prefix:   /admin/contacts
    
#News
hrom_news:
    resource: "@HROMNewsBundle/Resources/config/routing.yml"
    prefix:   /news

hrom_news_admin:
    resource: "@HROMNewsBundle/Resources/config/admin.yml"
    prefix:   /admin/news
    
#Cursus
hrom_school:
    resource: "@HROMCursusBundle/Resources/config/routing.yml"
    prefix:   /school
    
hrom_cursus_admin:
    resource: "@HROMCursusBundle/Resources/config/admin.yml"
    prefix:   /admin/cursus
    
#Gallery
hrom_gallery:
    resource: "@HROMGalleryBundle/Resources/config/routing.yml"
    prefix:   /gallery
    
hrom_gallery_admin:
    resource: "@HROMGalleryBundle/Resources/config/admin.yml"
    prefix:   /admin/gallery

#Events
hrom_events:
    resource: "@HROMEventsBundle/Resources/config/routing.yml"
    prefix:   /events
    
hrom_events_admin:
    resource: "@HROMEventsBundle/Resources/config/admin.yml"
    prefix:   /admin/events
    
#Partners
hrom_partners:
    resource: "@HROMPartnerBundle/Resources/config/routing.yml"
    prefix:   /partners
    
hrom_partners_admin:
    resource: "@HROMPartnerBundle/Resources/config/admin.yml"
    prefix:   /admin/partners
    
#FOSUser config    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
