<?php

namespace HROM\EventsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Counts events
     * 
     * @return integer
     */
    public function count() {
        $qb = $this->_em->createQueryBuilder();

        $qb
                ->select('count(event)')
                ->from('HROMEventsBundle:Event', 'event');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
