<?php

namespace HROM\ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    /**
     * Count contacts
     * 
     * @return integer
     */
    public function count() {
        $qb = $this->_em->createQueryBuilder();

        $qb
                ->select('count(contact)')
                ->from('HROMContactsBundle:Contact', 'contact');

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function queryFindByRole($role) {
        $qb = $this->_em->createQueryBuilder();
        
        $qb
                ->select('contact')
                ->from('HROMContactsBundle:Contact', 'contact')
                ->where('contact.roles LIKE :role')
                    ->setParameter('role', '%' . $role . '%');
        
        return $qb;
    }
    
    /**
     * Gives contact with $role
     * 
     * @param string $role
     * @return list
     */
    public function findByRole($role) {
        $qb = $this->queryFindByRole($role);
        
        return $qb->getQuery()->getResult();
    }
}
