<?php

namespace HROM\ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    /**
     * Count contacts
     * 
     * @return integer
     */
    public function count() {
        $qb = $this->_em->createQueryBuilder();

        $qb
                ->select('count(contact)')
                ->from('HROMContactsBundle:Contact', 'contact');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
