news_list:
    path:	/{page}
    defaults:	{ _controller: HROMNewsBundle:NewsAdmin:list, page: 1 }
    requirements:
        page:	(([1-9])+([0-9])*)

news_add:
    path: /add
    defaults: { _controller: HROMNewsBundle:NewsAdmin:add }
    
news_edit:
    path: /edit/{id}
    defaults: { _controller: HROMNewsBundle:NewsAdmin:edit }
    requirements:
        id: \d+

news_delete:
    path:	/delete/{id}
    defaults:	{ _controller: HROMNewsBundle:NewsAdmin:delete }
    requirements:
        id:	\d+