events_list:
    path:	/{page}
    defaults:	{ _controller: HROMEventsBundle:EventsAdmin:list, page: 1 }
    requirements:
        page:	(([1-9])+([0-9])*)

event_add:
    path: /add
    defaults: { _controller: HROMEventsBundle:EventsAdmin:add }
    
event_edit:
    path: /edit/{id}
    defaults: { _controller: HROMEventsBundle:EventsAdmin:edit }
    requirements:
        id: \d+

event_delete:
    path:	/delete/{id}
    defaults:	{ _controller: HROMEventsBundle:EventsAdmin:delete }
    requirements:
        id:	\d+