partners_list:
    path:	/{page}
    defaults:	{ _controller: HROMPartnerBundle:PartnerAdmin:list, page: 1 }
    requirements:
        page:	(([1-9])+([0-9])*)

partner_add:
    path: /add
    defaults: { _controller: HROMPartnerBundle:PartnerAdmin:add }
    
partner_edit:
    path: /edit/{id}
    defaults: { _controller: HROMPartnerBundle:PartnerAdmin:edit }
    requirements:
        id: \d+

partner_delete:
    path:	/delete/{id}
    defaults:	{ _controller: HROMPartnerBundle:PartnerAdmin:delete }
    requirements:
        id:	\d+