parameters:
#    hrom_partner.example.class: HROM\PartnerBundle\Example

services:
#    hrom_partner.example:
#        class: %hrom_partner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
