cursus_list:
    path:	/{page}
    defaults:	{ _controller: HROMCursusBundle:CursusAdmin:list, page: 1 }
    requirements:
        page:	(([1-9])+([0-9])*)

cursus_add:
    path: /add
    defaults: { _controller: HROMCursusBundle:CursusAdmin:add }
    
cursus_edit:
    path: /edit/{id}
    defaults: { _controller: HROMCursusBundle:CursusAdmin:edit }
    requirements:
        id: \d+

cursus_delete:
    path:	/delete/{id}
    defaults:	{ _controller: HROMCursusBundle:CursusAdmin:delete }
    requirements:
        id:	\d+