welcome:
    path:  /
    defaults: { _controller: HROMCoreBundle:Core:root }
home:
    path:	/home
    defaults:	{ _controller: HROMCoreBundle:Core:index }
school:
    path:  /school
    defaults: { _controller: HROMCoreBundle:Core:school }
calendar:
    path:  /calendar
    defaults: { _controller: HROMCoreBundle:Core:calendar }
contact_us:
    path:  /contactus
    defaults: { _controller: HROMCoreBundle:Core:contactUs }
links:
    path:  /links
    defaults: { _controller: HROMCoreBundle:Core:links }