parameters:
#    hrom_core.example.class: HROM\CoreBundle\Example

services:
#    hrom_core.example:
#        class: %hrom_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
