<?php

namespace HROM\CursusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursusRepository extends EntityRepository
{
    /**
     * Count cursus
     * 
     * @return integer
     */
    public function count() {
        $qb = $this->_em->createQueryBuilder();

        $qb
                ->select('count(cursus)')
                ->from('HROMCursusBundle:Cursus', 'cursus');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
